var recipeName="Creamy squash linguine";
var preprationTime="45";
var recipeBy="Jimmy Cutter";
var isVegetarian="true";
var calories="223.7";
console.log("Recipe Details");
console.log("--------------");
console.log("recipeName: "+recipeName);
console.log("preprationTime: "+preprationTime);
console.log("recipeBy: "+ recipeBy);
console.log("is Vegetarian Dish: "+isVegetarian);
console.log("calories: "+calories);
console.log("Recipe Details after Update");
console.log("----------------------------");
preprationTime="60";
console.log("recipeName: "+recipeName);
console.log("preprationTime: "+preprationTime);
console.log("recipeBy: "+ recipeBy+" "+"George");
console.log("is Vegetarian Dish: "+isVegetarian);
console.log("calories: "+calories);